### ISSUE TITLE
error with vnc

### ISSUE THREAD

**Issue by Trangoul1988** [NotTheRealJoe/docker-grass-desktop#1]
I'm trying to run it in a truenas as a docker, but:

![image](https://github.com/user-attachments/assets/0dc2f60d-6c23-4edc-812b-07044192de0f)

**Comment by NotTheRealJoe** [comment]
Hi @Trangoul1988. Thanks for trying out the project. I believe those messages are related to the VNC server trying to start some kind of hardware acceleration, which isn't available inside the container. However, this does not prevent it from actually starting. We can also see from the "Client handshake done." message that Grass Desktop is in fact running. Can you try connecting a VNC client and share any additional log output if it doesn't work?

**Comment by Trangoul1988** [comment]
Hello @NotTheRealJoe . Thank you for the fast reply.
I think you are right, I turned on the privileged mode, now I have some more log.
vnc client, just says failed to connect to server.

![image](https://github.com/user-attachments/assets/a4578b40-6c5e-4986-80da-12b3f258c07f)

**Comment by Trangoul1988** [comment]
Oh, now it's working, it was actually my bad, little tricky with truenas... everything works now

**Comment by grizlyadams** [comment]
what did you do in Truenas to get it working (I'm having the same issue in UnRaid)?
